import type { NextPage } from 'next'
import Head from 'next/head'
import CategoryCard from '../components/CategoryCard'
import styles from '../styles/Home.module.css'

const Home: NextPage = () => {
  return (
    <div className="container">
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.container}>
        <div className={styles.small}>
          <CategoryCard image="/images/xbox.jpeg" name="Xbox" />
          <CategoryCard image="/images/ps5.jpeg" name="PS5" />
          <CategoryCard image="/images/switch.jpeg" name="Switch" />
        </div>
        <div className={styles.large}>
          <CategoryCard image="/images/pc.jpeg" name="PC" />
          <CategoryCard
            image="/images/accessories.jpeg"
            name="Accessories"
          />
        </div>
      </main>
    </div>
  )
}

export default Home
